import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0f1418',
        'surface-dim': '#0f1418',
        'surface-bright': '#343a3e',
        'surface-container-lowest': '#0a0f12',
        'surface-container-low': '#171c20',
        'surface-container': '#1b2024',
        'surface-container-high': '#252b2e',
        'surface-container-highest': '#303539',
        'on-surface': '#dee3e8',
        'on-surface-variant': '#bdc8d1',
        'inverse-surface': '#dee3e8',
        'inverse-on-surface': '#2c3135',
        outline: '#87929a',
        'outline-variant': '#3e484f',
        'surface-tint': '#7bd0ff',
        primary: '#8ed5ff',
        'on-primary': '#00354a',
        'primary-container': '#38bdf8',
        'on-primary-container': '#004965',
        'inverse-primary': '#00668a',
        secondary: '#5de6ff',
        'on-secondary': '#00363e',
        'secondary-container': '#00cbe6',
        'on-secondary-container': '#00515d',
        tertiary: '#ffc176',
        'on-tertiary': '#472a00',
        'tertiary-container': '#f1a02b',
        'on-tertiary-container': '#613b00',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#c4e7ff',
        'primary-fixed-dim': '#7bd0ff',
        'on-primary-fixed': '#001e2c',
        'on-primary-fixed-variant': '#004c69',
        'secondary-fixed': '#a2eeff',
        'secondary-fixed-dim': '#2fd9f4',
        'on-secondary-fixed': '#001f25',
        'on-secondary-fixed-variant': '#004e5a',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb960',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        background: '#0f1418',
        'on-background': '#dee3e8',
        'surface-variant': '#303539',
      },
      fontFamily: {
        'playfair': ['Playfair Display', 'serif'],
        'inter': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-code': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
      },
      maxWidth: {
        container: '1280px',
      },
      boxShadow: {
        'glow': '0 0 15px rgba(56, 189, 248, 0.3)',
        'glow-lg': '0 0 24px rgba(56, 189, 248, 0.5)',
        'inner-glow': 'inset 0 1px 1px rgba(56, 189, 248, 0.1), 0 8px 32px rgba(0, 0, 0, 0.4)',
      },
      backdropBlur: {
        glass: '32px',
      },
      animation: {
        shimmer: 'shimmer 1.5s infinite',
        float: 'float 4s ease-in-out infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
    },
  },
  plugins: [],
  darkMode: 'class',
}
export default config
